# version
# services
# networks
# volumes
# secrets
# configs
# extensions

version: "3.8"


services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql # datas
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html # datas
    depends_on:
      - mariadb
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html # datas
    depends_on:
      - wordpress
    restart: unless-stopped
  networks:
    inception:
      name: inception
      #driver: bridge # default
  volumes:
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/cbolat/data/wordpress
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/cbolat/data/mariadb