version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: unless-stopped
  grafana:
    container_name: grafana
    build: ./requirements/bonus/grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: unless-stopped
  static_site:
    container_name: static_site
    build: ./requirements/bonus/static_site
    env_file:
      - .env
    ports:
      - "3030:3030"
    networks:
      - inception
    restart: unless-stopped
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbolat/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbolat/data/mariadb
